use_frameworks!

target 'RSAutoWebView_Example' do
  pod 'RSAutoWebView', :path => '../'

  target 'RSAutoWebView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
